### ISSUE TITLE
BUG: Wrong version set in pip

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/tcolorpy-feedstock#12]
In https://github.com/conda-forge/autoawq-feedstock/pull/7, we're running into
```
import: 'awq'
+ pip check
pytablewriter 1.2.0 has requirement tcolorpy<1,>=0.0.5, but you have tcolorpy 0.0.0.
```

In other words, from the POV of `pip`, tcolorpy as packaged by conda-forge has version `0.0.0`.

CC @conda-forge/tcolorpy

**Comment by hadim** [comment]
I got the same error:

```
pytablewriter 1.2.0 has requirement tcolorpy<1,>=0.0.5, but you have tcolorpy 0.0.0.
```

at https://github.com/conda-forge/lm_eval-feedstock/pull/15
